name: ISPC CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Prepare ISPC
      run: |
        wget -P /tmp -nv https://github.com/ispc/ispc/releases/download/v1.18.0/ispc-v1.18.0-linux.tar.gz
        tar -xf /tmp/ispc-v1.18.0-linux.tar.gz -C /opt/ 
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libomp-dev
    - name: Run ISPC
      run: |
        mkdir -p build && cd build
        cmake ..
        make
        ./ispc-vec-add
