name: ISPC CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Prepare ISPC
      run: |
        cd /opt
        wget https://github.com/ispc/ispc/releases/download/v1.18.0/ispc-v1.18.0-linux.tar.gz
        pwd
        ls
        tar -xf ispc-v1.18.0-linux.tar.gz
        mv ispc-v1.18.0-linux ispc
        ls
        
